from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class LoginUsuarioRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None, password=None):  # noqa: E501
        """LoginUsuarioRequest - a model defined in OpenAPI

        :param email: The email of this LoginUsuarioRequest.  # noqa: E501
        :type email: str
        :param password: The password of this LoginUsuarioRequest.  # noqa: E501
        :type password: str
        """
        self.openapi_types = {
            'email': str,
            'password': str
        }

        self.attribute_map = {
            'email': 'email',
            'password': 'password'
        }

        self._email = email
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'LoginUsuarioRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The loginUsuario_request of this LoginUsuarioRequest.  # noqa: E501
        :rtype: LoginUsuarioRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this LoginUsuarioRequest.

        Correo electrónico asociado a la cuenta perteneciente al usuario y junto a la contraseña permiten el acceso a la misma y a los servicios que ofrece la aplicación  # noqa: E501

        :return: The email of this LoginUsuarioRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this LoginUsuarioRequest.

        Correo electrónico asociado a la cuenta perteneciente al usuario y junto a la contraseña permiten el acceso a la misma y a los servicios que ofrece la aplicación  # noqa: E501

        :param email: The email of this LoginUsuarioRequest.
        :type email: str
        """

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this LoginUsuarioRequest.

        Contraseña que junto al correo electrónico se encuentran asociados a la cuenta perteneciente al usuario y le permiten el acceso a la misma y a los servicios que ofrece la aplicación  # noqa: E501

        :return: The password of this LoginUsuarioRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this LoginUsuarioRequest.

        Contraseña que junto al correo electrónico se encuentran asociados a la cuenta perteneciente al usuario y le permiten el acceso a la misma y a los servicios que ofrece la aplicación  # noqa: E501

        :param password: The password of this LoginUsuarioRequest.
        :type password: str
        """

        self._password = password
