from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class LoginUsuario200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token=None, id_usuario=None):  # noqa: E501
        """LoginUsuario200Response - a model defined in OpenAPI

        :param token: The token of this LoginUsuario200Response.  # noqa: E501
        :type token: str
        :param id_usuario: The id_usuario of this LoginUsuario200Response.  # noqa: E501
        :type id_usuario: int
        """
        self.openapi_types = {
            'token': str,
            'id_usuario': int
        }

        self.attribute_map = {
            'token': 'token',
            'id_usuario': 'idUsuario'
        }

        self._token = token
        self._id_usuario = id_usuario

    @classmethod
    def from_dict(cls, dikt) -> 'LoginUsuario200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The loginUsuario_200_response of this LoginUsuario200Response.  # noqa: E501
        :rtype: LoginUsuario200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self) -> str:
        """Gets the token of this LoginUsuario200Response.

        Si la operación se realiza exitosamente se devolverá un string, el cual representará el token de autenticación del usuario  # noqa: E501

        :return: The token of this LoginUsuario200Response.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this LoginUsuario200Response.

        Si la operación se realiza exitosamente se devolverá un string, el cual representará el token de autenticación del usuario  # noqa: E501

        :param token: The token of this LoginUsuario200Response.
        :type token: str
        """

        self._token = token

    @property
    def id_usuario(self) -> int:
        """Gets the id_usuario of this LoginUsuario200Response.

        Identificador único del usuario que ha iniciado sesión  # noqa: E501

        :return: The id_usuario of this LoginUsuario200Response.
        :rtype: int
        """
        return self._id_usuario

    @id_usuario.setter
    def id_usuario(self, id_usuario: int):
        """Sets the id_usuario of this LoginUsuario200Response.

        Identificador único del usuario que ha iniciado sesión  # noqa: E501

        :param id_usuario: The id_usuario of this LoginUsuario200Response.
        :type id_usuario: int
        """

        self._id_usuario = id_usuario
